# Generated by Django 3.2.9 on 2022-01-22 18:40

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='12', max_length=63),
        ),
    ]
