# Generated by Django 3.2.9 on 2022-01-22 20:42

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='58.859223547066584,25.751953125', max_length=63),
        ),
    ]
