# Generated by Django 3.2.9 on 2022-01-22 20:56

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220122_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=(-49.1607606, -22.2876834), max_length=63),
        ),
    ]
